import Image from "next/image";
import Banner from "./components/home-component/Banner";
import Product from "./components/home-component/Product";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Home() {
  
    //here we use seo factors and server side rendering so dont use client side feature instead break it into component and use it there if needed  
    metadata.title = "home page"
    metadata.description = "home description"


    
  return (
    <>

    <Banner/>
    <Product/>
    </>
  );
}
